language: java
dist: xenial
jdk:
  - openjdk17
before_install:
  - >-
    sudo sed -i
    -e '/local.*peer/s/postgres/all/'
    -e 's/peer\|md5/trust/g'
    /etc/postgresql/13/main/pg_hba.conf
  - sudo service postgresql@13-main restart
  - chmod +x mvnw
services:
  - postgresql
addons:
  postgresql: "13"
  apt:
    packages:
      - postgresql-13
env:
  global:
    - PGPORT=5433
before_script:
  - sudo psql -p 5433 -U postgres -c 'create database teste_livraria_crud_tdd;'
  - sudo psql -p 5433 -U postgres -c "create role adm with login superuser password '123456';"
after_success:
  - bash <(curl -s https://codecov.io/bash)